# 补充说明：spring的application.properties和application.yml存在哪个都行。甚至两个都存在spring会把两个合在一起都生效
person:
  userName: 张三 # 默认是双引号
  #  userName: "张三 \n 李四" # ""会将\n作为换行符输出,双引号不会转义(不改变换行符本身的意思)
  #  userName: '张三 \n 李四' #''会将\n作为字符串输出,单引号会转义(将换行符转译为了字符串)
  boss: true
  birth: 2019/12/9
  age: 18
  pet:
    name: 旺财
    weight: 99.99
  #  interests: [篮球,足球]
  interests:
    - 篮球
    - 足球
    - 18
  animal:
    - 阿猫
    - 阿狗
  #  score: {english: 80,math: 90}
  score:
    english: 80
    math: 90
  salarys:
    - 9999.98
    - 8888.98
  allPets:
    sick:
      - { name: 小强,weight: 10 }
      - name: 星猫
        weight: 20
      - name: 可达鸭
        weight: 30
    health: [ { name: 阿花,weight: 80 },{ name: 阿艹, weight: 90 } ]

spring:
  banner:
    image:
      bitdepth: 8
  mvc:
    # 开启rest风格,注意：这里因为web开发只能发送get/post，所以需要这里开启来指定额外的发送方式。
    # 如果是客户端，那么可以直接发送DELETE或者PATCH或者PUT等。无需开启该项。
    hiddenmethod:
      filter:
        enabled: true

    # 静态资源默认是/**，这里是配置加个前缀，注意：会导致静态资源首页功能失效，图标功能失效
    #static-path-pattern: /res/**

    # 开启基于请求参数的内容协商。效果是能配个参数（默认是format)代替浏览器请求头的的Accept值。手动指定浏览器能接收哪些参数
    contentnegotiation:
      favor-parameter: true

  web:
    resources:
      # 手动指定自定义静态资源路径，默认的静态4个静态资源访问路径全部失效
      static-locations: classpath:/customeStaticFile
#       禁用静态资源，所有的静态资源都访问不了
#      add-mappings: false

