server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#消费者将要访问的微服务名称（注册成功进nacos的微服务提供者）
#注意：这里可配可不配
service-url:
  nacos-payment-service: http://nacos-payment-provider




