itheima:
  resource:
    systemcode: shiro-mgt
  framework:
    jwt:
      base64-encoded-secret-key: sdfdsfdsfdsfdsfdsf
    shiro:
      redis:
        nodes: redis://127.0.0.1:6379
        connect-timeout: 6000
        connect-pool-size: 150
        connection-minimumidle-size: 30
        timeout: 6000
        global-session-timeout: 25200000
  datasource:
    shiro:
      work-id: 10
      primary-key: id
      data-source-name: shiro-data-source
      xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:10000/study_shiro_itheima?useSSL=false
      password: root
      username: root
      initial-size: 20
      max-active: 200
      max-life-time: 3600000
      min-idle: 10
      max-wait: 6000
      validation-query: select 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      remove-abandoned: false
      remove-abandoned-timeout: 60000
      log-abandoned: true
      filters: mergeStat
      type-aliases-package: com.itheima.shiro.pojo
      mapper-locations: classpath*:shiro/sqlmap*/*.xml
spring:
  aop:
    auto: true
    proxy-target-class: true
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  jta:
    atomikos:
      properties:
        log-base-dir: /Users/zhangyuhan/Work/log/study_shiro_itheima/shiro-mgt
        transaction-manager-unique-name: shiro-mgt
dubbo:
  application:
    name: springboot-shiro-mgt-01
    id: springboot-shiro-mgt-01
    logger: log4j2
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 21190
    threads: 200
    accesslog: /Users/zhangyuhan/Work/log/study_shiro_itheima/springboot-shiro-mgt.log
server:
  tomcat:
    uri-encoding: utf-8