server:
  port: 8001
spring:
  application:
    # 对应application列
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://127.0.0.1:10000/spring_cloud_study?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.study.springcloud.entities

eureka:
  instance:
    # 对应status列
    instance-id: payment8001
    # status服务实例悬浮显示ip和端口
    prefer-ip-address: true

    # 心跳时间和续约时间在开发时设置小些，保证服务关闭后，注册中心能即时剔除服务
    # 心跳发送时间：eureka客户端向服务端发送的心跳的时间间隔，单位为秒，默认30
    lease-renewal-interval-in-seconds: 1
    # 续约时间：eureka服务端在收到最后一次心跳后的等待时间上限，单位为秒，默认90，超时将剔除当前服务
    lease-expiration-duration-in-seconds: 2
  client:
    #是否将自己注册进eurekaServer,默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      # 集群版，注册进每个服务中心
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
